name: Build Hugo Blog

# Run the workflow when a change is merged into the 'main' branch
on:
  push:
    branches:
      - main

env:
  AWS_REGION: "eu-west-2"  # S3 bucket region

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true  # Use extended version if your blog uses SCSS

