name: Build Hugo Blog

# Run the workflow when a change is merged into the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true  # Use extended version if your blog uses SCSS

      # Step 3: Build the Hugo site
      - name: Build the site
        run: hugo

      # Optional: Save the build output (for debugging)
      - name: Upload public folder
        uses: actions/upload-artifact@v3
        with:
          name: hugo-build
          path: public/
