name: Build Hugo Blog

on:
  push:
    branches:
      - main  # Trigger workflow only when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Hugo using a prebuilt GitHub Action
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest' # Replace 'latest' with a specific version if needed
          extended: true         # Set to true if your blog uses Hugo extended features (e.g., SCSS)

      # Build the Hugo site
      - name: Build Hugo site
        run: hugo

      # Optional: Upload the built site as an artifact (useful for debugging or deployment)
      - name: Upload Hugo site artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hugo-site
          path: public/

